# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Lilikoi.Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework-version: [ 'net47', 'net48', 'net6.0', 'net7.0' ]

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          dotnet-quality: 'ga'

      - name: Install dependencies
        run: dotnet restore
      - name: Build for ${{ matrix.framework-version }}
        run: dotnet build Lilikoi.Tests --framework ${{ matrix.framework-version }} --configuration Release --no-restore
      - name: Test for ${{ matrix.framework-version }}
        run: dotnet test Lilikoi.Tests --framework ${{ matrix.framework-version }} --configuration Release --no-build --no-restore --verbosity normal
